/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'addExternalText' : IDL.Func([IDL.Text], [], []),
  'addPersistentCanister' : IDL.Func([IDL.Principal], [], []),
  'addRemoteCanister' : IDL.Func([IDL.Principal], [], []),
  'getExternalTexts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPersistentCanisters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRemoteCanisters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'addExternalText' : IDL.Func([IDL.Text], [], []),
    'addPersistentCanister' : IDL.Func([IDL.Principal], [], []),
    'addRemoteCanister' : IDL.Func([IDL.Principal], [], []),
    'getExternalTexts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPersistentCanisters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRemoteCanisters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };